### ISSUE TITLE
Document that it's not a "real" node stream.

### ISSUE THREAD

**Issue by ronag** [pinojs/thread-stream#12]
Might be worth explicitly stating that this is not a "real" node stream and does not implement the exact same behavior. If I didn't read the implementation I would have been a little confused.

**Comment by ronag** [comment]
I guess it will work as a target for `Readable.pipe` and `stream.pipeline`?

**Comment by mcollina** [comment]
That's the idea.

**Comment by mcollina** [comment]
Probably not because it only works with utf8 strings.

It works as a destination of pino ;).

**Comment by ronag** [comment]
No worries. Just took it for a ride and see if I could use it. Great idea. Maybe can be made more generic in the future.
