### ISSUE TITLE
Release without tests

### ISSUE THREAD

**Issue by crackcomm** [pinojs/thread-stream#129]
1. Is it necessary to release with tests?
2. If not, please make a patch release without tests.

Builds that depend on this package through Bazel are breaking because Bazel doesn't support directories with spaces.

**Comment by jsumners** [comment]
Sounds like an issue for your tooling to resolve.

**Comment by crackcomm** [comment]
> Sounds like an issue for your tooling to resolve.

It does indeed. It's not entirely possible though. I'm just looking for a quick workaround.
