### ISSUE TITLE
propagate errors to main thread

### ISSUE THREAD

**Issue by davidmarkclements** [pinojs/thread-stream#20]
as per https://github.com/pinojs/thread-stream/blob/main/lib/worker.js#L85

**Comment by glensc** [comment]
@davidmarkclements 

🚧 Never link to branches, share a permalink 🚧
- see https://news.ycombinator.com/item?id=8046710
  and https://help.github.com/articles/getting-permanent-links-to-files/
  and https://docs.gitlab.com/ee/user/shortcuts.html#project-files
- hit `y`
- and perhaps for https://github.com/josephfrazier/octopermalinker (GitHub)
