### ISSUE TITLE
Worker import fails for file paths with spaces under Yarn PnP

### ISSUE THREAD

**Issue by johndiiorio** [pinojs/thread-stream#60]
In `./lib/worker.js`, there is a `fn = realRequire(workerData.filename.replace('file://', ''))` call to handle requiring under PnP. Unfortunately, this line doesn't take into account the `pathToFileURL` call done in `./index.js > createWorker`. If the file path has spaces, it will be encoded like `file:///foo%20bar/`. The `realRequire` then cannot find this file and throws an exception.

One fix is to `decodeURIComponent` before requiring the file.

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by johndiiorio** [comment]
@mcollina I'll look into creating a pull request with tests. Thanks.
