### ISSUE TITLE
registry.unregister is not a function

### ISSUE THREAD

**Issue by Ali-Hussein-dev** [pinojs/thread-stream#93]
I don't use thread-stream directly it is used probably by Pino-pretty when building my Nextjs app, locally I can see these logs. 
current version pino-pretty: `7.6.1`
![thread-stream](https://user-images.githubusercontent.com/42802922/177530792-f447eb1c-509e-4856-a25f-6bd6f8b52161.jpg)

**Comment by Ali-Hussein-dev** [comment]
I see, the problem is the issue occurs in a mono repo (Nx workspace) where Nextjs apps are built successfully without logging any errors but one of them causes the error logs. So creating a mono repo with Pino-pretty will probably will not regenerate the error logs.

**Comment by mcollina** [comment]
Very likely this is a result of some issues in your build toolchain.
