### ISSUE TITLE
Propagate events from worker stream

### ISSUE THREAD

**Issue by Mogztter** [pinojs/thread-stream#97]
We've introduced a bunch of events on `pino-socket` but as far as I know it's not possible to listen to them as soon as we are using a ThreadStream.

Worker thread can communicate with the parent thread using [`require('worker_threads').parentPort.on('message')`](https://nodejs.org/docs/latest-v14.x/api/worker_threads.html#worker_threads_event_message). I think it would be nice to allow transport to publish events through this port:

```js
const parentPort = require('worker_threads').parentPort

const error = new Error('unable to write data to the TCP socket')
outputStream.emit('socketError', error)
if (parentPort) {
  parentPort.postMessage({ code: 'EVENT', name: 'socketError', args: [error] })
}
```

We will need to add a case in the `onWorkerMessage` function to propagate the event:

https://github.com/pinojs/thread-stream/blob/deaedaa03621b0955f64654d18ca136a2fc867a4/index.js#L152-L167

Something like:

```js
switch (msg.code) { 
  case 'EVENT': 
     stream.emit(msg.name, msg.args)
     break
}
```

With the above changes it's possible to write:

```js
const socketStream = pino.transport({
  target: "pino-socket",
  options: {
    address: tcpAddress,
    port: tcpPort,
    mode: "tcp",
    reconnect: true,
  }
})
// socketStream is a ThreadStream but events are propagated!
socketStream.on('socketError', (error) => {
  // do something!
})
```

If we don't want to propagate events but still allow transport to send post message then we should allow the code `EVENT`. In this case, we could write:

```js
const socketStream = pino.transport({
  target: "pino-socket",
  options: {
    address: tcpAddress,
    port: tcpPort,
    mode: "tcp",
    reconnect: true,
  }
})
// socketStream is a ThreadStream so we can listen to messages on the worker!
socketStream.worker.on('message', (msg) => {
  // do something!
})
```

**Comment by mcollina** [comment]
This would be nice to have. Would you like to send a PR?

**Comment by Mogztter** [comment]
Sure, I will submit a PR in the next days/weeks 👍🏻
